#!/bin/bash

dir_wallpaper="/home/garrido/Images/Wallpapers"
wallpaper=$(find "${dir_wallpaper}" -maxdepth 1 -mindepth 1 -type f -print0 -name "*.jpg" | \
    sort --zero-terminated --random-sort | sed 's/\d000.*//g')

ln -sf ${wallpaper} ${dir_wallpaper}/default

hsetroot -fill ${dir_wallpaper}/default &
