#!/bin/bash

screens=$(xrandr | awk '{if ($2 == "connected") print $1}')
nbr_screen=$(echo $screens | wc -w)
if [ $nbr_screen -eq 1 ]; then
    exit 0
fi

for screen in ${screens}
do
    # Get the best screen resolution
    next_line=$(xrandr | awk '/'${screen}'/{getline; print}')
    resolution=$(echo ${next_line} | awk '{print $1}')
    current=$(echo ${next_line} | awk '{if ($2 ~ "*") print}')
    if [ "$current" != "" ]; then
        echo "Monitor $screen is currently used"
        xrandr --output ${screen} --off
    else
        xrandr --output ${screen} --mode ${resolution}
    fi
done

# Reset wallpaper
/home/garrido/.config/openbox/scripts/change-wallpaper

# Disable beep
xset -b &

# Swap Caps_Lock and Escape keys
xmodmap /home/garrido/.Xmodmap &
