#!/bin/bash

IN="LVDS1"
EXT="HDMI3"

if (xrandr | grep "$EXT" | grep "+"); then
    xrandr --output $EXT --off --output $IN --auto
elif (xrandr | grep "$EXT" | grep " connected"); then
    xrandr --output $IN --off --output $EXT --mode 1920x1200
fi

# Reset wallpaper
/home/garrido/.config/openbox/scripts/change-wallpaper

# Disable beep
xset -b &

# Swap Caps_Lock and Escape keys
xmodmap /home/garrido/.Xmodmap &
