#!/bin/bash

if [ $1 = 'up' ]; then
    amixer set Master 5%+
elif [ $1 = 'down' ]; then
    amixer set Master 5%-
elif [ $1 = 'mute' ]; then
    amixer set Master toggle
else
    echo "Unknown control command: $1" >&2
    exit 1
fi

VOLUME=$(amixer sget Master | sed '/^ *Mono: /{s/^.*\[\(.*\)%\].*/\1/;p;};d;')
STATUS=$(amixer sget Master | awk '$1 == "Mono:" { print $NF; }')

if [ $STATUS = '[off]' ]; then
    ICON=audio-volume-muted-blocked-panel
else
    if [ $VOLUME -eq 0 ]; then
        ICON=audio-volume-off
    elif [ $VOLUME -lt 33 ]; then
        ICON=audio-volume-low
    elif [ $VOLUME -lt 66 ]; then
        ICON=audio-volume-medium
    else
        ICON=audio-volume-high
    fi
fi

VOLUME="${VOLUME}%"
notify-send " " "Current volume level ${VOLUME}" -i $ICON -t 1000
